<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="7.6990" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2022-03-31T20:31:05" tests="0" file="cypress/integration/secondTest.spec.js" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Test log out" timestamp="2022-03-31T20:31:05" tests="1" time="7.6990" failures="1">
    <testcase name="Test log out verify use can log out successfully" time="7.6990" classname="verify use can log out successfully">
      <failure message="Timed out retrying after 4000ms: expected &apos;&lt;ul.nav.navbar-nav.pull-xs-right&gt;&apos; to contain &apos;Sign up2&apos;" type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: expected '<ul.nav.navbar-nav.pull-xs-right>' to contain 'Sign up2'
    at Context.eval (http://localhost:4200/__cypress/tests?p=cypress\integration\secondTest.spec.js:107:27)]]></failure>
    </testcase>
  </testsuite>
</testsuites>